### ISSUE TITLE
Changing a value and how far the valid button is away from it

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#142] opened 2017-03-22 01:30 UTC
Say I am using SetValue.  I set the value to 5, I then select another field.  That change to value of 5 is lost, it is reverted to the previous value.  Is this the expected behavior.  If so, we need to rethink this logic.  User will not click apply after each row change.  Especially when it is 2.4 nautical miles to the south east.  

![image](https://cloud.githubusercontent.com/assets/2707285/24178134/8f681894-0e7d-11e7-911f-92fe59474462.png)

**Comment by MikeMillerGIS** [comment] 2017-03-22 02:24
think this is a bug, the button is on a southward migration.  Every time I select a new file, the button moves farther down
![image](https://cloud.githubusercontent.com/assets/2707285/24179361/14d6fcd2-0e85-11e7-97bd-190e75f1c229.png)

**Comment by SteveGrise** [comment] 2017-03-22 18:06
The expected behavior is that the stored values will only change when you select the Apply button. We could auto-save after each selection, but then there is an issue about allowing people to browse and experiment with options without saving the changes if they change their mind. We settled on the Apply button and then a Revert option on the file if you want to throw away a set of changes...

The Apply button moving around is odd, it may be a symptom of recent UI changes. The location of the Apply and and Preview window has become problematic as the size of the hidden/maximum Panel has grown with Domain Map and more complex mapping settings. It is growing due to the size of hidden UI elements that are only visible when the fields are selected. In your case where the Apply button has moved a lot there might be a large Domain Map or Value Map for one or more of the fields..

**Comment by MikeMillerGIS** [comment] 2017-03-22 19:46
Move apply button next to method, hide/disable when not required

**Comment by previnWong** [comment] 2017-03-29 18:36
Apply is next to the method chooser now. closing.

**Closed by previnWong** 2017-03-29 18:36 UTC
Labels: bug, fixed, Verified

**Comment by MikeMillerGIS** [comment] 2017-04-07 13:02
@SteveGrise I like the new button location, but should preview be up there too?
![image](https://cloud.githubusercontent.com/assets/2707285/24801160/f902db36-1b70-11e7-99bf-81e29abf8064.png)

**Comment by SteveGrise** [comment] 2017-04-07 13:37
i think it gives a good visual location/confirmation whenever you hit
apply. otherwise you won't see it unless you go looking... open to
suggestions

On 7 Apr 2017 9:02 a.m., "Michael Miller" <notifications@github.com> wrote:

@SteveGrise <https://github.com/SteveGrise> I like the new button location,
but should preview be up there too?
[image: image]
<https://cloud.githubusercontent.com/assets/2707285/24801160/f902db36-1b70-11e7-99bf-81e29abf8064.png>

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Esri/data-assistant/issues/142#issuecomment-292530349>,
or mute the thread
