### ISSUE TITLE
Methods not changing values when source field name = target field name

### ISSUE THREAD

**Issue by SteveGrise** [Esri/data-assistant#65] opened 2016-09-16 14:32 UTC
Always just seems to copy the source value, this was working on Pro 1.2 and no code changes were made.

**Comment by SteveGrise** [comment] 2016-09-16 21:07
@ChrisBuscaglia @chris-fox Guys I am seeing some arcpy.da cursor issues in Pro 1.3.1. Can you see if others are experiencing similar issues or if there is a known issue for this? 

I am getting the arcpy.da rows, setting values in that list, and then calling cursor.updateRow(row). The result is that the calculated field values are not being changed in the file geodatabase.

This is code that was working well in Pro 1.2 and also similar code worked fine in Desktop for a long time, so I am really puzzled.

**Comment by SteveGrise** [comment] 2016-10-04 22:13
There was an issue in my code, where the source and target names were the same the fields were being appended 2 times into the field list, and the values were not being set correctly.

**Comment by jessnoo** [comment] 2016-11-28 17:49
@SteveGrise What is the best way to test this? I understand that it has to do with the situation where the source and target field names are the same, but am confused about what the incorrect/unexpected behavior was.

**Comment by SteveGrise** [comment] 2016-11-28 22:06
Have source and target names the same and apply any method other than copy
or none. This was failing to produce the correct result - the target value
was just behaving like copy no matter what was selected.

**Comment by jessnoo** [comment] 2016-11-28 23:11
Ah ok -- Thanks @SteveGrise 

I will run through a sanity on all the methods to close this one out. In my previous testing, I did exercise a few with this base condition and did not have any issues.

- [ ] None
- [ ] Copy
- [ ] SetValue
- [ ] ValueMap
- [ ] ChangeCase
- [ ] Concatenate
- [ ] Left
- [ ] Right
- [ ] Substring
- [ ] Split
- [ ] ConditionalValue

**Comment by jessnoo** [comment] 2016-11-29 01:41
@SteveGrise with this test case, there were two methods that did not pass -- None and Substring.

Sample data: 
[Issue65SampleData.zip](https://github.com/Esri/data-assistant/files/617915/Issue65SampleData.zip)


**None** -- expected that result value to be empty (null) even though a source field was mapped.  Alternate test cases:  
(1) choose a source field with a different field name and choose null -- failed -- source was still mapped from the field with the same name
(2) choose (None) as the source field -- passed -- result was empty if there was no source field with the same name as the selected target field in the source dataset
(3) choose (None) as the source field -- failed-- when a field exists in the source dataset with the same name as the selected target field, the result was populated with the source value even though no Source field was selected and the Method was set to None.

![image](https://cloud.githubusercontent.com/assets/6181441/20693183/8a9dd488-b591-11e6-90ae-5f74318c38e4.png)

**Substring** -- the preview was correct, but the result was incorrect. In the following screenshot -- i expected 6 characters in the result, but only got 3. 

![image](https://cloud.githubusercontent.com/assets/6181441/20693208/b57c5aee-b591-11e6-9a83-f1cfe9c6ef23.png)

**Comment by jessnoo** [comment] 2016-11-29 01:42
@ChrisBuscaglia FYI above

**Comment by SteveGrise** [comment] 2016-11-30 18:47
Issues created by previous fix. @jessnoo ready for retest.

**Comment by jessnoo** [comment] 2016-12-01 18:41
@SteveGrise can you create a pull request to develop for these changes?  looks like maybe they were made in your fork?

and, if necessary, recompile the addin?  

i can validate and close the issue then.

@ChrisBuscaglia fyi

**Comment by SteveGrise** [comment] 2016-12-01 18:56
@jessnoo @ChrisBuscaglia pull request created from Sprint2 to develop, you should have the updated addin with that.

**Comment by ChrisBuscaglia** [comment] 2016-12-01 19:12
@jessnoo merged pull request into develop branch

**Comment by jessnoo** [comment] 2016-12-01 19:45
validated None and Substring methods fixed with commit https://github.com/Esri/data-assistant/commit/59d107689d831ddb44c5ca1ee1e52352e248670c

**Closed by jessnoo** 2016-12-01 19:45 UTC
Labels: fixed, retest
