### ISSUE TITLE
Using a layer from the TOC for a feature service - does not work - source to target

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#165] opened 2017-04-26 16:03 UTC
This service is not shared with everyone and is using https

![image](https://cloud.githubusercontent.com/assets/2707285/25444199/47cd42c2-2a78-11e7-8f0e-37a2632be5f9.png)

**Comment by MikeMillerGIS** [comment] 2017-04-26 16:03
fyi @ChrisBuscaglia

**Comment by MikeMillerGIS** [comment] 2017-04-26 16:04
using the url works fine
![image](https://cloud.githubusercontent.com/assets/2707285/25444252/763f81ce-2a78-11e7-832c-0dc8c1fd7089.png)

**Comment by SteveGrise** [comment] 2017-04-26 17:38
I'm not even sure how you added that - is the item a layer you selected from the combobox? I suspect there is something strange going on with the datasource property testing/concatenation... and http/https in the code

**Comment by SteveGrise** [comment] 2017-04-26 19:51
@MikeMillerGIS can you open up that service and send me the url in text form? I'm puzzled about the Service Name result and the http://https:// at the start of the url in the error message.

**Comment by MikeMillerGIS** [comment] 2017-04-26 19:53
Add any hosted FS to your TOC from the portal page.  That shows up in the drop down.

**Comment by MikeMillerGIS** [comment] 2017-04-26 19:54
here is what is passed in
Stormwater_OpenDrain_5015368ed0dc4f75a2103bb8dc7b3208\Storm Open Drains

source props
![image](https://cloud.githubusercontent.com/assets/2707285/25453908/b2bfb784-2a98-11e7-8770-c24ea2730bca.png)

**Comment by SteveGrise** [comment] 2017-04-26 20:00
Can you send me that long url in text form?

**Comment by MikeMillerGIS** [comment] 2017-04-26 20:04
https://services3.arcgis.com/xoil9QbyeUaxAZtF/arcgis/rest/services/Stormwater_OpenDrain_5015368ed0dc4f75a2103bb8dc7b3208/FeatureServer

**Comment by MikeMillerGIS** [comment] 2017-04-26 20:04
https://services3.arcgis.com/xoil9QbyeUaxAZtF/arcgis/rest/services/Stormwater_OpenDrain_5015368ed0dc4f75a2103bb8dc7b3208/FeatureServer

**Comment by SteveGrise** [comment] 2017-04-27 13:40
@ChrisBuscaglia @MikeMillerGIS this will need re-testing. I am not sure this fixes the issue, but it should at least provide a better error message. The key part of the error message is: 
![image](https://cloud.githubusercontent.com/assets/4749060/25485837/4a7bded8-2b2d-11e7-9f94-3d5ecc0512c9.png)

I am not able to reproduce that message, but I made 2 changes in the service name and layerid functions the I think addresses it.

**Comment by SteveGrise** [comment] 2017-04-27 13:41
see the funny http://https:// part of the url in the error message above...

**Comment by MikeMillerGIS** [comment] 2017-04-27 13:45
will test today

**Comment by previnWong** [comment] 2017-04-27 18:19
@SteveGrise , the issue is still there.  make sure that you are using a https, http works fine.
![image](https://cloud.githubusercontent.com/assets/11183838/25498036/52c608bc-2b3b-11e7-990e-e9f9275be412.png)

**Comment by SteveGrise** [comment] 2017-04-27 18:30
Ahh, there's a clue here - GIS Servers\https:// at the beginning seems to trip it up. Will take another look.

**Comment by SteveGrise** [comment] 2017-05-02 19:00
Made a small update today to ensure string handling - found an issue using https AGO tables.

**Comment by ChrisBuscaglia** [comment] 2017-05-03 00:03
@previnWong can you please verify this?

**Comment by previnWong** [comment] 2017-05-03 15:26
@SteveGrise @ChrisBuscaglia Seems to be working now for https feature services.  will test tables next.

**Comment by ChrisBuscaglia** [comment] 2017-05-04 16:51
Tables look OK from testing on my end - closing this issue.

**Comment by previnWong** [comment] 2017-05-04 18:08
@ChrisBuscaglia Are you seeing this behavior with the tables?

If I drag the FS into the TOC.  If I drag the table from TOC into the DA tool, it throws an error.
![image](https://cloud.githubusercontent.com/assets/11183838/25718133/d34134a2-30b9-11e7-8fd0-170d57697595.png)

![image](https://cloud.githubusercontent.com/assets/11183838/25718120/cc07b3b4-30b9-11e7-84c5-eb9a974db587.png)

If I drag the FS table from portal into the DA tool, then it stores the path correctly.
![image](https://cloud.githubusercontent.com/assets/11183838/25718159/e3fdfce4-30b9-11e7-9b13-43fca7a88372.png)

I know we got into a discussion about the tables not being in the drop down to select from and that it will not be addressed, but if I drag it from the TOC, shouldn't it still store the path?
Feel free to close if this is normal expected behavior, does not seem like it to me.

**Comment by previnWong** [comment] 2017-05-04 18:17
putting this known behavior in the wiki

**Comment by ChrisBuscaglia** [comment] 2017-05-04 18:41
@previnWong are you dragging it from the contents pane or the portal tab?

**Comment by ChrisBuscaglia** [comment] 2017-05-04 18:44
@previnWong if you navigate to the table via the browse... button does it work?

**Comment by previnWong** [comment] 2017-05-04 18:46
@ChrisBuscaglia 
Browse to table (works)
Drag from portal pane (works)
Drag from Content pane (error)

**Comment by ChrisBuscaglia** [comment] 2017-05-04 19:08
@previnWong @SteveGrise @MikeMillerGIS @jessnoo spoke with GP team - TableView is for tables and table views and is the preferred way to accept feature service tables.  Added an issue for the next version to be delivered over the summer with ArcGIS Pro 2.0.

https://github.com/Esri/data-assistant/issues/166

**Comment by previnWong** [comment] 2017-05-04 21:31
closing this since #166 is created.

**Closed by previnWong** 2017-05-04 21:31 UTC
Labels: bug, fixed, In Progress
