### ISSUE TITLE
Crash when data mapping - specific workflow with concatenate

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/data-assistant#56] opened 2016-07-26 20:32 UTC
Any dataset - please use the 'show results' option.  This appears to happen on a few workflows, but this is how I can reproduce it consistently and may provide some clues as to where it is happening elsewhere.

video: 
![da_crash](https://cloud.githubusercontent.com/assets/5614261/17154317/5b3d60be-5335-11e6-804e-0de69883ad34.gif)

**Comment by SteveGrise** [comment] 2016-07-27 13:16
Can I get the xml document? There must be something in that causing the issue.

**Comment by ChrisBuscaglia** [comment] 2016-08-08 16:30
This happens when creating a brand new XML from a target and source and field mapping for the first time.

**Comment by SteveGrise** [comment] 2016-08-24 18:02
I believe this was related to the other issue with missing Xml nodes causing an exception. Have not been able to reproduce since making that change.

**Comment by NikkiGolding** [comment] 2016-08-24 19:14
FYI @ChrisBuscaglia We will validate issues for release.

**Comment by ChrisBuscaglia** [comment] 2016-09-15 21:02
@SteveGrise Still crashing after changes for Sept. release

**Comment by SteveGrise** [comment] 2016-09-15 21:56
@ChrisBuscaglia I have never been able to reproduce this issue, and I thought maybe some of the other changes would have helped. I likely need to get source/target datasets and the project file to try to repro the issue. Does it happen on multiple machines?

**Comment by jessnoo** [comment] 2016-11-09 00:08
@SteveGrise This is still an issue with 1.4 Alpha 3
![image](https://cloud.githubusercontent.com/assets/6181441/20122563/8151070c-a5cd-11e6-90c1-9f254e86a0aa.png)

**Comment by SteveGrise** [comment] 2016-11-09 13:31
I need a reproducible case for this.

**Comment by jessnoo** [comment] 2016-11-09 19:57
@SteveGrise  I can consistently repro the crash behavior with these steps:

With this file: 
[issue76.zip](https://github.com/Esri/data-assistant/files/581622/issue76.zip)

1. Open a new, empty Pro 1.4 Alpha 3 project
2. Open the Data Mapper tool
3. Select the attached Issue76.xml s-t file
4. Click Fields tab
5. For LOWPARCELID, change the Method to Concatenate
6. Add LOWPARCELID
7. Add Unit
8. Try to add CVTTXCD -- **Notice** that the box doesn't check
9. Try to add CVTTXDSCRIP -- **Crash**


I suspect there may be two issues as this particular failure is different from the screenshot above, but it's a place to start.

Also attaching a crash dump file from the above repro steps: 
[ArcGISPro_11.4.0.6384_6545793F-AD37-4607-A40F-78BEFA9E9387_11_09_2016_11_18_23.zip](https://github.com/Esri/data-assistant/files/581712/ArcGISPro_11.4.0.6384_6545793F-AD37-4607-A40F-78BEFA9E9387_11_09_2016_11_18_23.zip)


Alternate steps that produced a failure, i was trying to shorten this workflow when i discovered the one above...

![image](https://cloud.githubusercontent.com/assets/6181441/20152059/84174df8-a671-11e6-85f6-5c3804c2d5b8.png)

**Comment by SteveGrise** [comment] 2016-11-15 13:45
I have been able to reproduce this issue. Working on a solution.

**Comment by SteveGrise** [comment] 2016-11-15 20:17
Sometimes when the user clicks on the checkboxes at the bottom edge of the screen a click event is sent, but the box is not checked. Had to improve the code to filter out these clicks because when the DataGrid items are recreated it was adding the item the unclicked list twice and causing an exception.

**Comment by ChrisBuscaglia** [comment] 2016-11-21 23:43
@SteveGrise I still can reproduce this one.  This was addressed with the latest addin from develop, right?

I can "highlight" a row by clicking to the right of the checkbox, clicking again right of the checkbox crashes ArcGIS Pro.

![gifcrash](https://cloud.githubusercontent.com/assets/5614261/20505368/3b5669ca-b001-11e6-82b5-203601407c68.gif)

**Comment by SteveGrise** [comment] 2016-11-21 23:52
@ChrisBuscaglia Looks like a different click issue. Will have to debug, strange behavior...

**Comment by SteveGrise** [comment] 2016-11-22 14:06
@ChrisBuscaglia I have a fix, in this case a double-click near the checkbox starts a CellEdit operation. It looks like setting the DataGrid property IsReadOnly="True" prevents that from happening. Should I apply to the develop branch, Sprint1, or Sprint2?

**Comment by SteveGrise** [comment] 2016-11-22 15:23
@ChrisBuscaglia checked in several changes that I believe resolves the issue to the Sprint2 branch.

**Comment by ChrisBuscaglia** [comment] 2016-11-22 16:25
@SteveGrise sounds good - we'll test in Sprint 2.

**Closed** 2016-11-28 17:48 UTC
Labels: bug, fixed, priority: high
