### ISSUE TITLE
Polygon simplification process failing on ArcGIS Pro 1.4

### ISSUE THREAD

**Issue by SteveGrise** [Esri/data-assistant#91] opened 2016-11-17 17:50 UTC
I cannot get arcpy.SimplifyPolygon_cartography to work with more than about 10k features at a time using the data in Issue #84. Whether from my DA script or an ArcGIS Pro Model it crashes Pro after loading the data into memory (per progress bar update). 

I tried with the original 800k+ features, 100k features, and 10k features. The first 10k records work, the second 10k records will crash Pro. I imported the shapefile data into a file gdb and ran repair geometry on the data first. Attempting now to do this with non-repaired geometries and other techniques to work around this.

Any ideas @ChrisBuscaglia @NikkiGolding @chris-fox ?

**Comment by SteveGrise** [comment] 2016-11-17 21:25
No luck today. I can simplify in ArcGIS desktop successfully, it crashes Pro 1.4 every time with this data. I have reduced from 800k features to a subset to avoid the out of memory error, but it still fails - likely with some specific features.

I have tried with repaired and unrepaired geometry, same results from what I can tell.

**Comment by SteveGrise** [comment] 2016-11-17 21:26
Here's the successful output in ArcCatalog 10.3 for the first 100k features.

![image](https://cloud.githubusercontent.com/assets/4749060/20408245/975135f6-ace2-11e6-8442-75fa4df25601.png)

**Comment by SteveGrise** [comment] 2016-11-17 21:53
Here's the successful output from Pro 1.3 for the same dataset.
![image](https://cloud.githubusercontent.com/assets/4749060/20409130/66692698-ace6-11e6-9804-e9bf66861cab.png)

**Comment by SteveGrise** [comment] 2016-11-17 22:56
Also confirmed the latest DA build works for these 100k features on Pro 1.3. Looks like a bug in Pro 1.4

**Comment by ChrisBuscaglia** [comment] 2016-11-18 16:52
@SteveGrise I'm able to reproduce.  I'm not able to run simplify, and the parameters have changed slightly since 1.3.

@chris-fox do you know who works on generalization these days to report?

**Comment by ChrisBuscaglia** [comment] 2016-11-18 21:24
```
def handleGeometryChanges(sourceDataset,targetLayer):
    # simplfiy polygons
    desc = arcpy.Describe(sourceDataset) # assuming local file gdb
    dataset = sourceDataset
    if desc.ShapeType == "Polygon" and (targetLayer.lower().startswith("gis servers") == True or targetLayer.lower().startswith("http://") == True):
        dataset = sourceDataset
    else:
        dataset = sourceDataset    

    return dataset
```

**Comment by ChrisBuscaglia** [comment] 2016-11-19 00:30
@SteveGrise @NikkiGolding @jessnoo 

This probably needs to be a separate issue - add Features to a (hosted) service fails to upload with large datasets (800,000 polygons).

The error is related to the JSON being constructed - it's too large and the reason for the simplification routine originally added.  This means that the routine is needed if we want to pursue this for December using this methodology.

### ```
Python Error messages:
Traceback Info:
  File "C:\Users\chri4819\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaPublish.py", line 251, in addFeatures
    featurejs = featureclass_to_json(sourceLayer)
  File "C:\Users\chri4819\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaPublish.py", line 323, in featureclass_to_json
    return json.loads(desc.json)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
Data Assistant Update Failed, see messages for details
```

**Comment by SteveGrise** [comment] 2016-11-19 02:18
I saw the same thing when I skipped simplification. If we can resolve this
#91 issue then the second one goes away, otherwise we'll have to deal with
this too.

**Comment by ChrisBuscaglia** [comment] 2016-11-21 16:35
@SteveGrise this has been addressed with ArcGIS Pro 1.4 Alpha 4.  Tested and verified @LindsayThomas can we get Steve this cut?

**Comment by LindsayThomas** [comment] 2016-11-21 17:05
@ChrisBuscaglia @SteveGrise do you have access to this cut via the Early Adopter program?

**Comment by SteveGrise** [comment] 2016-11-21 18:38
Looks like it:
[image: Inline image 1]

**Comment by SteveGrise** [comment] 2016-11-21 18:41
@ChrisBuscaglia @NikkiGolding @jessnoo @LindsayThomas Looks like I can get to the Alpha 4. Just want to confirm that Sprint2 will involve dev/release/test on this version, not Alpha3, correct ?

**Comment by ChrisBuscaglia** [comment] 2016-11-21 19:33
@SteveGrise Correct, we will move all testing to Alpha 4 (retest anything that has been verified on Alpha 3).

**Comment by ChrisBuscaglia** [comment] 2016-11-28 17:49
Closing this issue, revisit append with a future release - currently, Alpha 4 is working with the simplification process

**Closed by ChrisBuscaglia** 2016-11-28 17:49 UTC
