### ISSUE TITLE
Crash when using xml with character in different encoding then what is expected

### ISSUE THREAD

**Issue by chris-fox** [Esri/data-assistant#53] opened 2016-06-29 16:23 UTC
Load the configuration file below in the Data Mapper -> Crash

It is failing when attempting to load the xml on the single quote character below in New Year's Day.

DESCRIPT="There is no collection on New Year’s Day, Memorial Day, July 4, Labor Day, Thanksgiving or Christmas"

[SourceTarget5.zip](https://github.com/Esri/data-assistant/files/339712/SourceTarget5.zip)

FYI @LindsayThomas, @ChrisBuscaglia

**Comment by ChrisBuscaglia** [comment] 2016-07-08 15:27
@NikkiGolding @SteveGrise we should get this in for August/Sept

**Comment by SteveGrise** [comment] 2016-07-25 15:11
Looks like Xml encoding in Python 3 has changed from version 2. The issue is not an apostrophe (which is working in the same record "Lindsay Thomas' trash pickup"), it's actually a right-side quotation mark that is not valid in a UTF encoding (byte x92). 

Will try to write this correctly from python, and also work around it in C# in case it sneaks in somehow.

**Comment by SteveGrise** [comment] 2016-07-27 14:36
With python 3 this appears to work for creating the file:
attrval = row[f].encode('utf-8', errors='replace').decode('utf-8',errors='backslashreplace')

I have also fixed it on the C# side to read a binary memory stream which seems to work nicely.

Note that the document I received must have been hand edited since the python script to create the problematic text would not have processed that string correctly. As a result, this is a situation that could never happen until now unless the Xml document was edited by hand and an unusual copy/paste was done to edit the document.

But it is worth fixing all of this to handle non-English characters and many other utf-8 chars that could be an issue for international users.

**Comment by chris-fox** [comment] 2016-07-27 17:23
@SteveGrise, I may have edited the XML document while debugging, but this crash definitely occurred with the tools themselves without manual editing. @LindsayThomas was getting the crash prepping her demo at the UC. She may have the original File GDB that created the original issue.

**Comment by LindsayThomas** [comment] 2016-07-27 20:39
@SteveGrise Let me dig this up. I have about a million copies from trying to troubleshoot. Let me get the right one.

**Comment by SteveGrise** [comment] 2016-07-28 13:49
It's ok, my main point was that I think I have a solution now that handles
creating the file (python) and reading the file (c#). It may be that the
database did have those types of characters in there, it's just I'm pretty
sure it would have failed in the original file creation rather than just
the C# code.

I have pasted a bunch of non-typical characters into my test database, I
can export with python and then view the attributes in the Preview tool.
The final result looks the same as the source rows.

**Comment by LindsayThomas** [comment] 2016-07-28 14:41
[PublicWorksUpdates.gdb.zip](https://github.com/Esri/data-assistant/files/388586/PublicWorksUpdates.gdb.zip)

Hi Steve, this is a version of the geodatabase that fails. 
When I created the data I was using ArcCatalog\ArcMap.

**Comment by SteveGrise** [comment] 2016-07-28 14:51
Great, I was able to run through the tools, here is the result after
running Preview... works end-to-end in my test environment now.

[image: Inline image 1]

**Comment by LindsayThomas** [comment] 2016-07-28 14:55
@SteveGrise Great News.

**Comment by SteveGrise** [comment] 2016-08-24 18:04
Have checked in the fix.

**Comment by NikkiGolding** [comment] 2016-08-24 19:15
FYI @ChrisBuscaglia We will validate issues for release.

**Comment by jessnoo** [comment] 2016-11-09 00:09
@ChrisBuscaglia @chris-fox validated

**Closed by jessnoo** 2016-11-09 00:09 UTC
Labels: bug, fixed
