### ISSUE TITLE
New mapping file fails to complete

### ISSUE THREAD

**Issue by jessnoo** [Esri/data-assistant#58] opened 2016-08-25 18:44 UTC
With the lastest development cut on Pro 1.3, the new mapping file tool completes successfully but does not create a file.  It reports that the target layer isn't a feature service layer when it is.

steps to repro:

1. Publish district dataset shared in issue #53 by Lindsay T as a hosted feature service in ArcGIS Online (attached below for reference)
2. Create a new map in pro with the source FC and published feature service as layers
3. Click "New File"
4. Set source as the local fgdb district feature class 
5. Set target as the published feature service
6. Run tool -- receive message:
![image](https://cloud.githubusercontent.com/assets/6181441/17981546/fdd626cc-6ab8-11e6-9b70-350e5175b64b.png)
[PublicWorksUpdates.gdb.zip](https://github.com/Esri/data-assistant/files/437814/PublicWorksUpdates.gdb.zip)

Also reproed with the parcel layer shipped with Community Parcels
![image](https://cloud.githubusercontent.com/assets/6181441/17981570/15f4aeae-6ab9-11e6-9d7d-74109fd76225.png)

@SteveGrise what do you think?

FYI @NikkiGolding @ChrisBuscaglia

**Comment by jessnoo** [comment] 2016-08-25 18:48
point of clarification -- i'm using the released 1.3 version. (NOT a daily or special build)

**Comment by SteveGrise** [comment] 2016-08-25 18:54
I have been working on 1.2, will need to do some testing to prepare for 1.3
release.

**Comment by ChrisBuscaglia** [comment] 2016-08-25 19:15
@jessnoo Does this work in ArcGISPro 1.2?  There was this issue that was fixed...#51

**Comment by jessnoo** [comment] 2016-08-25 19:26
@ChrisBuscaglia  i didn't test in 1.2, i can circle back on that if we feel like it's relevant?

no -- the tool did not create any file -- there are kind of two issues here:

1. the tool says it's not a feature service layer when it is
2. the tool says it finished successfully when it didn't

**Comment by ChrisBuscaglia** [comment] 2016-08-25 20:06
@jessnoo I'm trying to determine if the ArcGIS Pro 1.2 exhibits the same behavior, that would be really bad since it's the version that the tool is supported on.

**Comment by jessnoo** [comment] 2016-08-25 23:54
@ChrisBuscaglia @SteveGrise 

Retested with 1.2 and the New File tool ran successfully (iow passed the test) with the same workflow described above.

![image](https://cloud.githubusercontent.com/assets/6181441/17989652/ed700b56-6ae3-11e6-8646-9607e9cb5584.png)

looks like there is a bug at 1.3 with the August version of the New File tool. 

@NikkiGolding FYI

**Comment by SteveGrise** [comment] 2016-08-26 12:59
I believe this 1.3 issue is similar to what someone had found at the UC. It
looks like something changed in the GP Parameters in 1.3, hopefully it
addresses the workaround we did in 1.2 to catch feature service vs feature
layer selections.

**Comment by ChrisBuscaglia** [comment] 2016-08-26 17:57
@SteveGrise 

I can reproduce this with the 1.2 released addin with ArcGIS Pro 1.3.

I did however get around the problem by dragging and dropping the feature service directly into the tool from my portal (appending the layerid).  

![8-26-2016 10-53-13 am](https://cloud.githubusercontent.com/assets/5614261/18015227/94e7e6b4-6b7b-11e6-9a2f-f32d945f936d.png)

Since every customer with 1.2 has been prompted to install ArcGIS Pro 1.3, they will hit this issue.  We'll need to get it addressed for our **Sept**. release.

Can you find some time to take a look and estimate how long a fix may take?  I've looked into the tool to see where I could get around the feature layer check, but it's not a sound fix.

Chris

**Comment by SteveGrise** [comment] 2016-08-26 18:28
@ChrisBuscaglia sure, I can take a look. I'm sure there's a fix for it, shouldn't be too hard.

**Comment by SteveGrise** [comment] 2016-08-31 16:18
Seems to me like there is a significant change in service urls in ArcGIS Pro 1.3(.1). I'm pretty sure in earlier versions that catalogPath and path properties for services would return the /0 (/<id>) style urls. Now I see url strings like '/L0PARCELS'. 

@ChrisBuscaglia I'd like to verify that this behaviour is now 'normal' in Pro. It's a big change.

I've worked around it and I believe the issue is resolved in the August2016 branch.

![service string](https://cloud.githubusercontent.com/assets/4749060/18136935/7fbf11b6-6f74-11e6-9df1-2f21e3f8a27f.PNG)

**Comment by NikkiGolding** [comment] 2016-08-31 16:52
@chris-fox can you talk with the Pro team and get some info?

**Comment by chris-fox** [comment] 2016-09-01 13:08
@NikkiGolding, I spoke with the GP team and this is not expected behavior, they were actually already aware of it and had logged a bug, CR340485. The expected behavior is it should return the url to the layer or table within the feature service.

**Comment by SteveGrise** [comment] 2016-09-01 13:56
Ok, I worked around it in the code - if the layer id startswith 'L' then it
will strip off the L and drop the feature service name that is appended
after the numeric layerid. If just the numeric value is passed then the
code does nothing.

I did notice that arcpy.Describe works better in 1.3, looks like some of
the complexity in figuring out layer properties (path) is no longer needed.

**Comment by ChrisBuscaglia** [comment] 2016-09-06 16:13
@NikkiGolding Just getting to this, has anyone tested this?

**Comment by NikkiGolding** [comment] 2016-09-06 16:21
@ChrisBuscaglia not yet. @jessnoo did not get to it before she left on vacation. @lindsayking will work on this today so we can get moving on getting it signed.

**Comment by lindsayking** [comment] 2016-09-06 17:34
@ChrisBuscaglia @NikkiGolding   When testing with the latest in the August branch, I am still encountering an issue using Jess's repro steps in the original comment above.
1) Improvement: the tool no longer reports that it completes successfully when it doesn't  (it no longer reports success when it is really a failure)
2) However, the tool fails, reporting that the PublicWorksDistrict does not appear to be a feature service layer.  It also says that PublicWorksDistricts does not have create and delete privileges, but it does, according to its [endpoint](http://services.arcgis.com/8KEQHzVdm3qDSW1h/arcgis/rest/services/PublicWorksDistricts/FeatureServer/0).

![fails](https://cloud.githubusercontent.com/assets/4316336/18284020/096a686e-741d-11e6-8557-f681b812cef2.png)


Note, the tool DOES complete successfully when - instead of dragging the feature service layer into the input from my contents pane - I browse to the feature service in my content and input it that way:
![passes](https://cloud.githubusercontent.com/assets/4316336/18283963/c3ed86c2-741c-11e6-8d0c-71e17c68fa30.png)

**Comment by NikkiGolding** [comment] 2016-09-06 17:52
@SteveGrise Can you take a look?

**Comment by SteveGrise** [comment] 2016-09-06 18:08
In my testing the layer was prefixed with an 'L', like '/L0PublicWorksDistrict'. In this example it looks like just '/0PublicWorksDistrict'. I'm just guessing at the logic here since I am working around a bug in Pro (Chris Fox referenced it but I don't think I have access to the bug to read about it), but maybe I should change the logic so that I basically just extract the number from this string and drop any letters? @lindsayking @NikkiGolding @chris-fox

**Comment by SteveGrise** [comment] 2016-09-06 18:41
Made a change to just take the first integer in the last part of the layer url. Committed to the August 2016 branch.

**Comment by lindsayking** [comment] 2016-09-06 18:44
@SteveGrise  Thanks.  I'll re-test now.

**Comment by lindsayking** [comment] 2016-09-06 19:16
@SteveGrise @NikkiGolding @ChrisBuscaglia 

The latest change looks good.  Using the same workflow as above, I am now seeing the tool complete successfully. 
![fixpasses](https://cloud.githubusercontent.com/assets/4316336/18287025/4cdc1d24-742a-11e6-85a7-4dd4c042a718.png)

My only concern is that it now looks like it checks to service/REST capabilities twice.  Is that an issue, or are we good to proceed with what we have?

**Comment by SteveGrise** [comment] 2016-09-06 19:43
@lindsayking I think you used the same source and target? If you use a file gdb/feature service combo it should check each one separately.

**Comment by lindsayking** [comment] 2016-09-06 20:08
@SteveGrise   -   I used a file gdb feature class as the source dataset and the feature service layer as the target.  In this case, I dragged them into the tool from my contents pane, and they had the same name.  This is the scenario in which I see the checks to the service twice.

When I change the name of the file gdb layer and re-run the tool, however, I don't see the checkts reported twice.  I'm using the same inputs as in the first scenario, just with the fgdb layer renamed.

**Comment by SteveGrise** [comment] 2016-09-06 20:40
@lindsayking the issue is that from the GP script I just get the layer name and then it's just picking up the first layer with that name both times. It's actually not going to create the file the way you want.

I'm not sure if I can figure out from the GP tool parameter which of the layers with the same name to use, this all happens before the script runs. For example, in Pro GP tool I see PublicWorksDistrict:1 and :2 in the dialog after dragging, but in the script I only receive: PublicWorksDistrict without any of the sequence info.

This is a different issue than the one we saw before, I'm not sure how to work around it.

**Closed** 2016-09-06 22:48 UTC
Labels: bug, fixed
